### ISSUE TITLE
Failing to Generate Coverage for Some Files

### ISSUE THREAD

**Issue by DeedleFake** [rpl/flow-coverage-report#183]
I'm running flow-coverage-report against a moderately large codebase. It's failing get coverage information for some files, seemingly at random. I'm not sure what's different about these files from the others.

An example:

```
ERROR Collecting coverage data from scripts/uglify.js { Error: Command failed: flow coverage --json scripts/uglify.js
    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: 'flow coverage --json scripts/uglify.js' }
```

Interestingly, running `flow coverage --json scripts/uglify.js` manually works completely fine. The number of files it fails on also seems to vary depending on what the `-c` flag has been set to. If it's left on the default of 1, it fails on about a third to half of the files, and setting it to `4` causes it to fail on _all_ of the files in the entire codebase.

**Comment by kiparenkomb** [comment]
Hi everybody!
I have the same error and I cannot understand what the problem is?

**Comment by rpl** [comment]
@kiparenkomb `VERBOSE=1 flow-coverage-report ...` may be able to produce some additional info about what is going on.
